Repository crime-capture-tv/server, pull requests merged in 2023-09, with the labels that each got.

#10 Feature/swagger : Crime Video Entity 생성
  src/main/java/com/mtvs/crimecapturetv/domain/video/command/aggregate/entity/CrimeVideo.java
Labels: 🌟feature

#11 Feature/store : Store entity 구성
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/StoreDTO.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/entity/Store.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/entity/enumType/StoreType.java
  src/main/java/com/mtvs/crimecapturetv/store/command/controller/StroreController.java
  src/main/java/com/mtvs/crimecapturetv/store/command/repository/StoreRepository.java
  src/main/java/com/mtvs/crimecapturetv/store/command/service/StroreService.java
  src/main/java/com/mtvs/crimecapturetv/store/query/controller/QueryStoreController.java
  src/main/java/com/mtvs/crimecapturetv/store/query/repository/QueryStoreRepository.java
  src/main/java/com/mtvs/crimecapturetv/store/query/repository/StoreMapper.java
  src/main/java/com/mtvs/crimecapturetv/store/query/service/QueryStoreService.java
Labels: 🌟feature

#12 Feature/userEntity : User Entity 추가
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/entity/User.java
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/entity/enumtype/UserRole.java
Labels: 🌟feature

#19 Feature/springSecurity : Spring Security 적용
  src/main/java/com/mtvs/crimecapturetv/configuration/SecurityConfig.java
  src/main/java/com/mtvs/crimecapturetv/configuration/login/UserDetail.java
  src/main/java/com/mtvs/crimecapturetv/configuration/login/UserDetailServiceImpl.java
  src/main/java/com/mtvs/crimecapturetv/exception/ErrorCode.java
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/dto/request/CommandUserLoginRequest.java
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/SecurityLoginController.java
  src/main/java/com/mtvs/crimecapturetv/user/command/repository/CommandUserRepository.java
  src/main/java/com/mtvs/crimecapturetv/user/command/service/CommandUserService.java
  src/main/resources/templates/TestLogin.html
Labels: 🌟feature

#21 Feature/video : 범죄영상 등록기능 구현
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/aggregate/dto/AiCrimeAnalyzeResponse.java
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/aggregate/dto/CreateCrimeVideoRequest.java
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/aggregate/dto/CreateCrimeVideoResponse.java
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/aggregate/dto/CrimeVideoDTO.java
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/aggregate/entity/CrimeVideo.java
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/controller/CommandCrimeVideoController.java
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/repository/CommandCrimeVideoRepository.java
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/service/CommandCrimeVideoService.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/command/aggregate/dto/CommandExampleDTO.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/command/aggregate/entity/Example.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/command/aggregate/vo/ExampleVO.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/command/controller/CommandExampleController.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/command/repository/CommandRepository.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/command/service/CommandExampleService.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/query/aggregate/dto/ExampleDTO.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/query/aggregate/entity/Example.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/query/controller/QueryExampleContorller.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/query/repository/ExampleMapper.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/query/repository/QueryExampleRepository.java
  src/main/java/com/mtvs/crimecapturetv/domain/exampleDomain/query/service/QueryExampleService.java
Labels: 🌟feature

#22 Feature/store : 점포 저장 기능 구현
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/StoreDTO.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/request/CommandStoreCreateRequest.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/entity/Store.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/entity/enumType/StoreType.java
  src/main/java/com/mtvs/crimecapturetv/store/command/controller/CommandStoreController.java
  src/main/java/com/mtvs/crimecapturetv/store/command/controller/StroreController.java
  src/main/java/com/mtvs/crimecapturetv/store/command/repository/CommandStoreRepository.java
  src/main/java/com/mtvs/crimecapturetv/store/command/repository/StoreRepository.java
  src/main/java/com/mtvs/crimecapturetv/store/command/service/CommandStoreService.java
  src/main/java/com/mtvs/crimecapturetv/store/command/service/StroreService.java
Labels: 🌟feature

#25 [BugFix#16] 점포 저장 기능 수정
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/response/CommandStoreCreateResponse.java
Labels: 🌟feature

#26 Feat/store : 점포 수정, 삭제, 조회 기능 구현
  src/main/java/com/mtvs/crimecapturetv/exception/ErrorCode.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/StoreDTO.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/request/CommandStoreDeleteRequest.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/request/CommandStoreUpdateRequest.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/response/CommandStoreCreateResponse.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/response/CommandStoreDeleteResponse.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/response/CommandStoreUpdateResponse.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/entity/Store.java
  src/main/java/com/mtvs/crimecapturetv/store/command/controller/CommandStoreController.java
  src/main/java/com/mtvs/crimecapturetv/store/command/repository/CommandStoreRepository.java
  src/main/java/com/mtvs/crimecapturetv/store/command/service/CommandStoreService.java
  src/main/java/com/mtvs/crimecapturetv/store/query/repository/StoreMapper.java
Labels: 🌟feature, 🔄️refactoring

#27 Feature/email : 이메일 인증 기능 구현
  build.gradle
  src/main/java/com/mtvs/crimecapturetv/configuration/EmailConfig.java
  src/main/java/com/mtvs/crimecapturetv/configuration/SecurityConfig.java
  src/main/java/com/mtvs/crimecapturetv/configuration/login/RedisConfig.java
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/CommandUserController.java
  src/main/java/com/mtvs/crimecapturetv/user/command/service/EmailService.java
  src/main/resources/application.yml
Labels: 🌟feature

#37 BugFix/redisConfig : RedisConfig, EmailConfig수정
  src/main/java/com/mtvs/crimecapturetv/configuration/EmailConfig.java
  src/main/java/com/mtvs/crimecapturetv/configuration/login/RedisConfig.java
Labels: 🐞bugfix

#39 Feature/board : 문의 게시판 CRUD 기능 구현
  src/main/java/com/mtvs/crimecapturetv/board/command/aggregate/dto/BoardDTO.java
  src/main/java/com/mtvs/crimecapturetv/board/command/aggregate/dto/request/CommandBoardCreateRequest.java
  src/main/java/com/mtvs/crimecapturetv/board/command/aggregate/dto/request/CommandBoardDeleteRequest.java
  src/main/java/com/mtvs/crimecapturetv/board/command/aggregate/dto/request/CommandBoardUpdateRequest.java
  src/main/java/com/mtvs/crimecapturetv/board/command/aggregate/dto/response/CommandBoardCreateResponse.java
  src/main/java/com/mtvs/crimecapturetv/board/command/aggregate/dto/response/CommandBoardDeleteResponse.java
  src/main/java/com/mtvs/crimecapturetv/board/command/aggregate/dto/response/CommandBoardUpdateResponse.java
  src/main/java/com/mtvs/crimecapturetv/board/command/aggregate/entity/Board.java
  src/main/java/com/mtvs/crimecapturetv/board/command/aggregate/entity/enumType/BoardType.java
  src/main/java/com/mtvs/crimecapturetv/board/command/controller/CommandBoardController.java
  src/main/java/com/mtvs/crimecapturetv/board/command/repository/CommandBoardRepository.java
  src/main/java/com/mtvs/crimecapturetv/board/command/service/CommandBoardService.java
  src/main/java/com/mtvs/crimecapturetv/exception/ErrorCode.java
  src/main/java/com/mtvs/crimecapturetv/store/command/service/CommandStoreService.java
Labels: 🌟feature

#40 Feat/store : 우편번호 검색 API 추가
  src/main/java/com/mtvs/crimecapturetv/board/command/aggregate/dto/response/CommandBoardListResponse.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/StoreDTO.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/request/CommandStoreCreateRequest.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/request/CommandStoreDeleteRequest.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/request/CommandStoreUpdateRequest.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/response/CommandStoreCreateResponse.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/dto/response/CommandStoreListResponse.java
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/entity/Store.java
  src/main/java/com/mtvs/crimecapturetv/store/command/controller/CommandStoreController.java
  src/main/java/com/mtvs/crimecapturetv/store/command/service/CommandStoreService.java
  src/main/java/com/mtvs/crimecapturetv/store/query/controller/QueryStoreController.java
  src/main/java/com/mtvs/crimecapturetv/store/query/repository/QueryStoreRepository.java
  src/main/java/com/mtvs/crimecapturetv/store/query/service/QueryStoreService.java
  src/main/resources/application.yml
  src/main/resources/templates/store-registform.html
Labels: 🌟feature

#42 Feature/alarm : 알림 기능 기본 설정
  src/main/java/com/mtvs/crimecapturetv/exception/ErrorCode.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/aggregate/dto/response/CommandNotificationResponse.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/aggregate/entity/Notification.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/aggregate/entity/enumtype/NotificationType.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/controller/CommandNotificationController.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/repository/CommandNotificationRepository.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/service/CommandNotificationService.java
Labels: 🌟feature

#43 Feature/userValidation : 이메일로 아이디 찾기, 비밀번호 재 생성 및 추가 기능 구현
  build.gradle
  src/main/java/com/mtvs/crimecapturetv/configuration/AccessDeniedHandlerImpl.java
  src/main/java/com/mtvs/crimecapturetv/configuration/CustomAuthenticationProvider.java
  src/main/java/com/mtvs/crimecapturetv/configuration/SecurityConfig.java
  src/main/java/com/mtvs/crimecapturetv/configuration/login/UserDetail.java
  src/main/java/com/mtvs/crimecapturetv/exception/ErrorCode.java
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/dto/request/CommandFindByEmailRequest.java
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/dto/request/CommandFindPasswordRequest.java
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/dto/request/CommandUserJoinRequest.java
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/dto/request/CommandUserJoinResponse.java
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/entity/User.java
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/CommandUserController.java
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/SecurityLoginController.java
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/homeController.java
  src/main/java/com/mtvs/crimecapturetv/user/command/repository/CommandUserRepository.java
  src/main/java/com/mtvs/crimecapturetv/user/command/service/CommandUserService.java
  src/main/java/com/mtvs/crimecapturetv/user/command/service/EmailService.java
Labels: 🌟feature

#45 Refactoring/store : store entity 컬럼명 수정
  src/main/java/com/mtvs/crimecapturetv/store/command/aggregate/entity/Store.java
Labels: 🔄️refactoring

#46 Feature/alarm : 알람 기능 구현
  src/main/java/com/mtvs/crimecapturetv/notification/command/aggregate/dto/response/CommandNotificationResponse.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/aggregate/entity/enumtype/NotificationType.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/controller/CommandNotificationController.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/repository/CommandNotificationRepository.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/repository/EmitterRepository.java
  src/main/java/com/mtvs/crimecapturetv/notification/command/service/CommandNotificationService.java
  src/main/java/com/mtvs/crimecapturetv/user/command/repository/CommandUserRepository.java
  src/test/java/com/mtvs/crimecapturetv/notification/command/service/CommandNotificationServiceTest.java
Labels: 🌟feature

#48 Bugfix/userNo : User Entity 대문자 수정
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/dto/UserDto.java
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/entity/User.java
Labels: 🐞bugfix

#53 Feature/video 영상 처리결과에 따른 DB저장 로직 추가
  build.gradle
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/aggregate/entity/CrimeVideo.java
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/controller/CommandCrimeVideoController.java
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/service/CommandCrimeVideoService.java
Labels: 🌟feature

#54 Feature/loginFront : login 프론트 연결
  src/main/java/com/mtvs/crimecapturetv/configuration/SecurityConfig.java
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/SecurityLoginController.java
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/homeController.java
  src/main/resources/static/bootstrap/css/style.css
  src/main/resources/templates/index.html
  src/main/resources/templates/users/find-id.html
  src/main/resources/templates/users/find-pw.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/register.html
Labels: 🎨design, 🌟feature

#56 Feature/joinFront : join, login 프론트 연결
  build.gradle
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/CommandUserController.java
  src/main/java/com/mtvs/crimecapturetv/user/command/service/EmailService.java
  src/main/resources/static/bootstrap/css/login.css
  src/main/resources/static/bootstrap/css/style.css
  src/main/resources/static/bootstrap/img/logo.png
  src/main/resources/templates/common/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/users/find-pw.html
  src/main/resources/templates/users/login.html
  src/main/resources/templates/users/register.html
Labels: 🎨design, 🌟feature

#59 Feature/mypage : Mypage 기능 추가
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/dto/request/CommandMyPageEditRequest.java
  src/main/java/com/mtvs/crimecapturetv/user/command/aggregate/dto/response/CommandMyPageInfoResponse.java
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/CommandMyPageController.java
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/MyPageController.java
  src/main/java/com/mtvs/crimecapturetv/user/command/service/CommandMyPageService.java
  src/main/java/com/mtvs/crimecapturetv/user/command/service/CommandUserService.java
Labels: 🌟feature

#60 Feature/board,store의 regist,list양식 추가
  build.gradle
  src/main/java/com/mtvs/crimecapturetv/user/command/controller/homeController.java
  src/main/resources/static/bootstrap/css/index.css
  src/main/resources/static/bootstrap/css/sb-admin-2.min.css
  src/main/resources/static/bootstrap/css/store.css
  src/main/resources/templates/boards/board-list.html
  src/main/resources/templates/boards/board.html
  src/main/resources/templates/common/header.html
  src/main/resources/templates/common/navbar.html
  src/main/resources/templates/index.html
  src/main/resources/templates/stores/store-regist.html
  src/main/resources/templates/stores/store.html
  src/main/resources/templates/stores/zipcode.html
Labels: 🌟feature

#68 Bugfix/css : 전체 사이드, 헤더, 푸터 수정
  src/main/java/com/mtvs/crimecapturetv/domain/crimevideo/command/controller/CrimeVideoController.java
  src/main/resources/templates/boards/board-list.html
  src/main/resources/templates/boards/board.html
  src/main/resources/templates/index.html
  src/main/resources/templates/stores/store-list.html
  src/main/resources/templates/stores/store-regist.html
  src/main/resources/templates/users/myPage.html
  src/main/resources/templates/users/myPageEdit.html
  src/main/resources/templates/videos/allVideoDetail.html
  src/main/resources/templates/videos/videoDetail.html
  src/main/resources/templates/videos/videoList.html
Labels: 🐞bugfix, 🎨design
